name: "Windows CI"
on: push

jobs:
  windows-script-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        script:
          - initialize_windows_settings.ps1 restore_power_settings.ps1
          - winget.ps1
          - optional_softwares.ps1
    steps:
      - uses: actions/checkout@v5
      - name: Run ${{ matrix.script }}
        run: |
          $scripts = "${{ matrix.script }}".Split(" ")
          foreach ($s in $scripts) {
            powershell -ExecutionPolicy Bypass -File $s
          }
        working-directory: ./scripts
