name: "Windows CI"
on: push
jobs:
  windows-setup-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Windows
        run: |
            cd .\scripts
            powershell -ExecutionPolicy Bypass -File "initialize_windows_settings.ps1"
            powershell -ExecutionPolicy Bypass -File "windowssetup.ps1"
